language: python
python:
  - 3.6

sudo: required
services:
  - docker

before_install:
  - pip install poetry
install:
  - poetry develop

script:
  - flake8 .
  - coverage run --source tmn -m pytest
  - coverage report
  - codecov
