language: python

python:
  - 3.6
  - 3.5
before_install:
  - pip install poetry
install:
  - poetry develop

jobs:
  include:

  - stage: Lint
    script:
    - flake8 .

  - stage: Tests
    script:
      - coverage run --source tmn -m pytest
      - coverage report
      - codecov
